language: python

python:
  - "3.6"

install:

  - pip install -r requirements.txt
  - pip install codecov coveralls
    


script:
  - py.test -v --cov-report term-missing --cov  app

after_success:
  - coveralls
  - codecov --token=03631114-bc1a-4a9d-be2e-b8db77f27d78